name: "Ren'Py setup"
description: "Install, build, and test Ren'Py games"
branding:
  color: blue
  icon: aperture
inputs:
  action:
    description: "What should be done with the action"
    default: install
  install_dir:
    description: "Where Ren'Py should be installed"
    required: false
  # Install action
  android_properties:
    description: Configuration properties to use when building android releases
    required: false
  android_aab_properties:
    description: If provided, overrides android_properties for Android App Bundle releases
    required: false
  android_apk_properties:
    description: If provided, overrides android_properties for Universal APK releases
    required: false
  android_sdk:
    description: "Whether to install the android SDK"
    required: false
  android_sdk_owner:
    description: "If android_sdk_install_input is not provided, the identity to declare when installing the android SDK"
    required: false
  android_sdk_install_input:
    description: "Input for the SDK installation process"
    required: false
  dlc:
    description: "List of dlcs to install"
    required: false
  live2d:
    description: "Live2D url of the file to install (Live2D won't be installed if this is not set)"
    required: false
  update_path:
    description: "Whether the install directory should be added to the PATH"
    required: false
  version:
    description: "Ren'Py version to install"
    required: false
  # All non-install actions
  game:
    description: "Path to the game's directory"
    required: false
  java_home:
    description: "Path to a Java 8 SDK used for android builds and installation"
    required: false
  # Android build/distribute action
  build_type:
    description: "Specifies whether an APK or AAB archive should be built"
    required: false
    default: apk
  # Distribute action
  packages:
    description: "List of release packages to build"
    required: false
  # All distribute-like actions
  out_dir:
    description: "Where the generated files should be saved"
    required: false
  # Exec action
  run:
    description: "The arguments that should be passed to Ren'Py as a string"
    required: false
  # translate action
  language:
    description: "The languages for which translations should be updated"
    required: false
    default: None
  # Lint action has no inputs
outputs:
  install_dir:
    description: "The directory where Ren'Py is installed"
  python_path:
    description: "The Python executable provided by Ren'Py"
  renpy_path:
    description: "The Ren'Py executable"
runs:
  using: "node16"
  main: "dist/setup/index.js"
