name: Build testing

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'package*.json'
      - 'tsconfig.json'

env:
  NODE_VERSION: 16.x

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - run: printf "\\nshow_your_bravery.txt" >> .gitignore
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: testing
          commit_message: Build develop branch
          push_options: --force
          create_branch: true
