# Based on actions/reusable-workflows/.github/workflows/basic-validation.yml
name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - releases/*
    tags:
      - v*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  NODE_VERSION: 16.x
  ANDROID_NDK_HOME: ""

jobs:
  test:
    runs-on: ${{ matrix.operating-systems }}
    strategy:
      fail-fast: false
      matrix:
        operating-systems:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot'
          java-version: '8'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run prettier
        run: npm run format-check

      - name: Run linter
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test -- --coverage

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/clover.xml
          flags: ${{ matrix.operating-systems }}

      - name: Audit packages
        run: npm audit --audit-level=high
        if: ${{inputs.enable-audit}}
